movable_area:
  ros__parameters:
    frame_id: "map"
    namespace: "movable_area"
    marker.id: 0
    marker.scale: 0.1
    marker.color.r: 1.0
    marker.color.g: 0.0
    marker.color.b: 1.0
    marker.color.a: 1.0
    area.x: [0.0,1.8]
    area.y: [0.0,3.5]
    area.z: 0.0
    publsih_rate_ms: 100