start_area_left:
  ros__parameters:
    frame_id: "field"
    namespace: "start_left_area"
    marker.id: 0
    marker.scale: 0.1
    marker.color.r: 0.0
    marker.color.g: 0.0
    marker.color.b: 1.0
    marker.color.a: 1.0
    area.x: [0.0,1.5]
    area.y: [3.5,5.0]
    area.z: 0.0
    publsih_rate_ms: 100