field_area:
  ros__parameters:
    frame_id: "field"
    namespace: "field_area"
    marker.id: 0
    marker.scale: 0.1
    marker.color.r: 0.87
    marker.color.g: 0.62
    marker.color.b: 0.52
    marker.color.a: 1.0
    area.x: [0.0,3.0]
    area.y: [0.0,5.0]
    area.z: 0.0
    publsih_rate_ms: 100